spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mes_db
    username: admin
    password: 123456

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO