-- =========================================================
-- V1__create_schema.sql
-- Initial schema for Chinese Learning System
-- Database: PostgreSQL
-- =========================================================


-- =========================================================
-- 1. ROLES
-- Corresponding entity: Role
-- =========================================================

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    name VARCHAR(50) NOT NULL,

    description VARCHAR(255),

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pk_roles
        PRIMARY KEY (id),

    CONSTRAINT uk_roles_name
        UNIQUE (name)
);


-- =========================================================
-- 2. USERS
-- Corresponding entity: User
-- =========================================================

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    username VARCHAR(50) NOT NULL,

    email VARCHAR(150) NOT NULL,

    password VARCHAR(100) NOT NULL,

    full_name VARCHAR(100) NOT NULL,

    avatar_url VARCHAR(500),

    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    email_verified BOOLEAN NOT NULL DEFAULT FALSE,

    last_login_at TIMESTAMP(6) WITHOUT TIME ZONE,

    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

    updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pk_users
        PRIMARY KEY (id),

    CONSTRAINT uk_users_username
        UNIQUE (username),

    CONSTRAINT uk_users_email
        UNIQUE (email)
);


-- =========================================================
-- 3. USER_ROLES
-- Join table for User.roles ManyToMany relationship
-- =========================================================

CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,

    role_id BIGINT NOT NULL,

    CONSTRAINT pk_user_roles
        PRIMARY KEY (user_id, role_id),

    CONSTRAINT uk_user_roles
        UNIQUE (user_id, role_id),

    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id)
        REFERENCES roles (id)
        ON DELETE CASCADE
);


CREATE INDEX idx_user_roles_role_id
    ON user_roles (role_id);


-- =========================================================
-- 4. REFRESH_TOKENS
-- Corresponding entity: RefreshToken
-- =========================================================

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,

    token_hash VARCHAR(64) NOT NULL,

    user_id BIGINT NOT NULL,

    expires_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

    revoked BOOLEAN NOT NULL DEFAULT FALSE,

    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT pk_refresh_tokens
        PRIMARY KEY (id),

    CONSTRAINT uk_refresh_tokens_token_hash
        UNIQUE (token_hash),

    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);


CREATE INDEX idx_refresh_user
    ON refresh_tokens (user_id);